### ISSUE TITLE
Several errors

### ISSUE THREAD

**Issue by mfabianrares** [satriaajiputra/imagebam-api#1]
Where is vendor/autoload.php?
Uncaught Error: Class 'ImageBamAPI\ImageBam'

**Comment by mfabianrares** [comment]
I just messaged the support team to install the composer for me, because I don't have ssh access.
After installing that, everything should work fine?

**Comment by satriaajiputra** [comment]
Yes, if you get some errors after doing that procedure, tell to me in this issue

**Comment by mfabianrares** [comment]
I installed the composer, executed 'composer require satmaxt/imagebam' already too, with success, but when trying to access implementation index.php I get http error 500.
What should I do? I edited the api keys and secrey key in config/imagebam.php

HTTP ERROR 500

**Comment by mfabianrares** [comment]
error log
[22-Oct-2019 03:23:17 UTC] PHP Warning:  require(/home/rareseu/public_html/fl/imagebam/implementation/../vendor/autoload.php): failed to open stream: No such file or directory in /home/rareseu/public_html/fl/imagebam/implementation/index.php on line 5
[22-Oct-2019 03:23:17 UTC] PHP Fatal error:  require(): Failed opening required '/home/rareseu/public_html/fl/imagebam/implementation/../vendor/autoload.php' (include_path='.:/opt/cpanel/ea-php72/root/usr/share/pear') in /home/rareseu/public_html/fl/imagebam/implementation/index.php on line 5

**Comment by mfabianrares** [comment]
what's your requirements?
Problem 1
    - The requested package satmaxt/imagebam No version set (parsed as 1.0.0) is satisfiable by satmaxt/imagebam[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

**Comment by mfabianrares** [comment]
Now I think I resolved that. from up, now I have this problem
`Stack trace:
#0 /home/rareseu/public_html/fl/imagebam/src/ImageBamAPI/ImageBam.php(29): ImageBamAPI\RequestToken->runRequestToken()
#1 /home/rareseu/public_html/fl/imagebam/implementation/index.php(24): ImageBamAPI\ImageBam->__construct('yourapi', 'yoursecret')
#2 {main}
  thrown in /home/rareseu/public_html/fl/imagebam/src/ImageBamAPI/RequestToken.php on line 71
[22-Oct-2019 03:55:37 UTC] PHP Fatal error:  Uncaught Exception: Failed while getting token data: oauth_problem=consumer_key_unknown in /home/rareseu/public_html/fl/imagebam/src/ImageBamAPI/RequestToken.php:71
Stack trace:
#0 /home/rareseu/public_html/fl/imagebam/src/ImageBamAPI/ImageBam.php(29): ImageBamAPI\RequestToken->runRequestToken()
#1 /home/rareseu/public_html/fl/imagebam/implementation/index.php(24): ImageBamAPI\ImageBam->__construct('yourapi', 'yoursecret')
#2 {main}
  thrown in /home/rareseu/public_html/fl/imagebam/src/ImageBamAPI/RequestToken.php on line 71`

**Comment by satriaajiputra** [comment]
> Now I think I resolved that. from up, now I have this problem
> `Stack trace: #0 /home/rareseu/public_html/fl/imagebam/src/ImageBamAPI/ImageBam.php(29): ImageBamAPI\RequestToken->runRequestToken() #1 /home/rareseu/public_html/fl/imagebam/implementation/index.php(24): ImageBamAPI\ImageBam->__construct('yourapi', 'yoursecret') #2 {main} thrown in /home/rareseu/public_html/fl/imagebam/src/ImageBamAPI/RequestToken.php on line 71 [22-Oct-2019 03:55:37 UTC] PHP Fatal error: Uncaught Exception: Failed while getting token data: oauth_problem=consumer_key_unknown in /home/rareseu/public_html/fl/imagebam/src/ImageBamAPI/RequestToken.php:71 Stack trace: #0 /home/rareseu/public_html/fl/imagebam/src/ImageBamAPI/ImageBam.php(29): ImageBamAPI\RequestToken->runRequestToken() #1 /home/rareseu/public_html/fl/imagebam/implementation/index.php(24): ImageBamAPI\ImageBam->__construct('yourapi', 'yoursecret') #2 {main} thrown in /home/rareseu/public_html/fl/imagebam/src/ImageBamAPI/RequestToken.php on line 71`

Please create your API client first at [http://www.imagebam.com/sys/API/clients](http://www.imagebam.com/sys/API/clients)

**Comment by mfabianrares** [comment]
I changed them now.
After I submit the verifier token, http error 500

**Comment by mfabianrares** [comment]
`Stack trace:
#0 /home/rareseu/public_html/fl/imagebam/src/ImageBamAPI/ImageBam.php(84): ImageBamAPI\RequestAccessToken->runRequestToken()
#1 /home/rareseu/public_html/fl/imagebam/implementation/index.php(36): ImageBamAPI\ImageBam->requestAccessToken('-------------SECRET---------')
#2 {main}
  thrown in /home/rareseu/public_html/fl/imagebam/src/ImageBamAPI/RequestAccessToken.php on line 88
[22-Oct-2019 04:01:27 UTC] PHP Warning:  fopen(/home/rareseu/public_html/fl/imagebam/config/../implementation/cache/imagebam.dat): failed to open stream: No such file or directory in /home/rareseu/public_html/fl/imagebam/implementation/index.php on line 27
[22-Oct-2019 04:01:27 UTC] PHP Warning:  fwrite() expects parameter 1 to be resource, bool given in /home/rareseu/public_html/fl/imagebam/implementation/index.php on line 28
[22-Oct-2019 04:01:27 UTC] PHP Warning:  fclose() expects parameter 1 to be resource, bool given in /home/rareseu/public_html/fl/imagebam/implementation/index.php on line 29
[22-Oct-2019 04:01:31 UTC] PHP Warning:  fopen(/home/rareseu/public_html/fl/imagebam/config/../implementation/cache/imagebam.dat): failed to open stream: No such file or directory in /home/rareseu/public_html/fl/imagebam/implementation/index.php on line 27
[22-Oct-2019 04:01:31 UTC] PHP Warning:  fwrite() expects parameter 1 to be resource, bool given in /home/rareseu/public_html/fl/imagebam/implementation/index.php on line 28
[22-Oct-2019 04:01:31 UTC] PHP Warning:  fclose() expects parameter 1 to be resource, bool given in /home/rareseu/public_html/fl/imagebam/implementation/index.php on line 29
[22-Oct-2019 04:01:31 UTC] PHP Warning:  fopen(/home/rareseu/public_html/fl/imagebam/config/../implementation/cache/imagebam.dat): failed to open stream: No such file or directory in /home/rareseu/public_html/fl/imagebam/implementation/index.php on line 27
[22-Oct-2019 04:01:31 UTC] PHP Warning:  fwrite() expects parameter 1 to be resource, bool given in /home/rareseu/public_html/fl/imagebam/implementation/index.php on line 28
[22-Oct-2019 04:01:31 UTC] PHP Warning:  fclose() expects parameter 1 to be resource, bool given in /home/rareseu/public_html/fl/imagebam/implementation/index.php on line 29
[22-Oct-2019 04:01:31 UTC] PHP Fatal error:  Uncaught Exception: Failed while getting token data: oauth_problem=token_rejected in /home/rareseu/public_html/fl/imagebam/src/ImageBamAPI/RequestAccessToken.php:88`

**Comment by mfabianrares** [comment]
I thinl the problem is because I dont have that cache file imagebam.dat

**Comment by satriaajiputra** [comment]
> `Stack trace: #0 /home/rareseu/public_html/fl/imagebam/src/ImageBamAPI/ImageBam.php(84): ImageBamAPI\RequestAccessToken->runRequestToken() #1 /home/rareseu/public_html/fl/imagebam/implementation/index.php(36): ImageBamAPI\ImageBam->requestAccessToken('-------------SECRET---------') #2 {main} thrown in /home/rareseu/public_html/fl/imagebam/src/ImageBamAPI/RequestAccessToken.php on line 88 [22-Oct-2019 04:01:27 UTC] PHP Warning: fopen(/home/rareseu/public_html/fl/imagebam/config/../implementation/cache/imagebam.dat): failed to open stream: No such file or directory in /home/rareseu/public_html/fl/imagebam/implementation/index.php on line 27 [22-Oct-2019 04:01:27 UTC] PHP Warning: fwrite() expects parameter 1 to be resource, bool given in /home/rareseu/public_html/fl/imagebam/implementation/index.php on line 28 [22-Oct-2019 04:01:27 UTC] PHP Warning: fclose() expects parameter 1 to be resource, bool given in /home/rareseu/public_html/fl/imagebam/implementation/index.php on line 29 [22-Oct-2019 04:01:31 UTC] PHP Warning: fopen(/home/rareseu/public_html/fl/imagebam/config/../implementation/cache/imagebam.dat): failed to open stream: No such file or directory in /home/rareseu/public_html/fl/imagebam/implementation/index.php on line 27 [22-Oct-2019 04:01:31 UTC] PHP Warning: fwrite() expects parameter 1 to be resource, bool given in /home/rareseu/public_html/fl/imagebam/implementation/index.php on line 28 [22-Oct-2019 04:01:31 UTC] PHP Warning: fclose() expects parameter 1 to be resource, bool given in /home/rareseu/public_html/fl/imagebam/implementation/index.php on line 29 [22-Oct-2019 04:01:31 UTC] PHP Warning: fopen(/home/rareseu/public_html/fl/imagebam/config/../implementation/cache/imagebam.dat): failed to open stream: No such file or directory in /home/rareseu/public_html/fl/imagebam/implementation/index.php on line 27 [22-Oct-2019 04:01:31 UTC] PHP Warning: fwrite() expects parameter 1 to be resource, bool given in /home/rareseu/public_html/fl/imagebam/implementation/index.php on line 28 [22-Oct-2019 04:01:31 UTC] PHP Warning: fclose() expects parameter 1 to be resource, bool given in /home/rareseu/public_html/fl/imagebam/implementation/index.php on line 29 [22-Oct-2019 04:01:31 UTC] PHP Fatal error: Uncaught Exception: Failed while getting token data: oauth_problem=token_rejected in /home/rareseu/public_html/fl/imagebam/src/ImageBamAPI/RequestAccessToken.php:88`

Try to create cache folder inside implementation folder. I will fix this at next version

**Comment by satriaajiputra** [comment]
Fixed at #3

**Comment by mfabianrares** [comment]
worked just with creating the folder inside implementation.
should I redownload and doing all steps again?

**Comment by mfabianrares** [comment]
Now works okay.
Could u help me to return only "thumbnail" as php after running the api?

**Comment by mfabianrares** [comment]
and also, it works with multiple files? i added multiple to input type file, but even if I choose 3 files, just first it uploads

**Comment by satriaajiputra** [comment]
> Now works okay.
> Could u help me to return only "thumbnail" as php after running the api?

You can return only thumbnail. Because the result format is an object, you can use this method and following [the result format](https://github.com/satriaajiputra/imagebam-api#example-output)
```php
$uploaded = $image->uploadImage($data);
echo $uploaded->rsp->image->thumbnail;
```
